### ISSUE TITLE
re draw tab control, add close button 

### ISSUE THREAD

**Issue by SZ559** [SZ559/Well-Trajectory-Visualization-GUI-#28] opened 2020-05-18 01:30 UTC

**Comment by SZ559** [comment] 2020-05-18 01:30
https://blog.csdn.net/u013944260/article/details/76720853

**Comment by SZ559** [comment] 2020-05-18 01:31
https://blog.csdn.net/a4600646/article/details/101816271?utm_medium=distribute.pc_relevant.none-task-blog-BlogCommendFromBaidu-7.nonecase&depth_1-utm_source=distribute.pc_relevant.none-task-blog-BlogCommendFromBaidu-7.nonecase

**Comment by kristol07** [comment] 2020-05-18 01:33
#27

**Comment by kristol07** [comment] 2020-05-18 01:33
Duplicate of #27

**Closed as completed** 2020-05-18 01:35 UTC
Labels: duplicate
